#!/bin/sh

set -e
ANSI_RED='\033[0;31m'
ANSI_GREEN='\033[0;32m'
ANSI_YELLOW='\033[1;33m'
ANSI_RESET='\033[0m'

PATH_PROJECT=/var/www/confmap
PATH_PUBLIC=/var/www/confmap/public
PATH_CONFIG=/etc/arris/livemap.confmap
# PATH_STORAGE_LINKED=${PATH_PUBLIC}/storage
PATH_CACHE_SMARTY=${PATH_PROJECT}/cache

PHP_VERSIONS=$(ps -e -o stat,command | grep -E '^Ss\s+php-fpm' | grep -E '[0-9]+\.[0-9]+' -o)

case "$1" in
    configure)
        echo "\n ${ANSI_YELLOW} Running CONFMAP post-install tasks... ${ANSI_RESET} \n"

        echo "Checking Application config... "
        if [ -e "${PATH_CONFIG}/common.conf" ]; then
            echo "${ANSI_GREEN} COMMON.CONF file found ${ANSI_RESET}";
        else
            echo "${ANSI_RED} COMMON.CONF file not found! ${ANSI_RESET}" ;
        fi

        # для confmap storage скопируем ручками

        # https://stackoverflow.com/questions/5767062/how-to-check-if-a-symlink-exists
        echo "Relinking favicon.ico"
        rm -f ${PATH_PUBLIC}/favicon.ico
        ln -s ${PATH_PUBLIC}/frontend/favicons/favicon.ico ${PATH_PUBLIC}/favicon.ico
        echo "${ANSI_YELLOW} Favicon symlink created. ${ANSI_RESET}"

        echo "Cleaning SMARTY Cache..."
        if [ -d "${PATH_CACHE_SMARTY}" ]; then
            rm -f ${PATH_CACHE_SMARTY}/*
            echo "${ANSI_GREEN} Cleared. ${ANSI_RESET}"
        fi

        echo "Fixing access rights..."
        chown -R www-data:www-data ${PATH_PROJECT}/*
        echo "${ANSI_GREEN} Ok. ${ANSI_RESET}"

        echo
        echo "Restarting all running php-fpm processes..."
        for version in $PHP_VERSIONS; do echo "Restarting ${ANSI_YELLOW}php${version}-fpm${ANSI_RESET} process..."; systemctl restart php${version}-fpm; done
        echo "${ANSI_GREEN}Finished.${ANSI_RESET}"

        echo
        echo "${ANSI_YELLOW} ... post-install finished. ${ANSI_RESET}"
        echo

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
